title: Default Page
preset: page
fields:
  titel:
    label: hoofdtitel
    type: text
    size: small
  sub_titel:
    label: subtitel
    type: text
    size: small
  waar_titel:
    label: titel
    type: text
    size: small
  waar_tekst_intro:
    label: subtitel
    type: textarea
    size: large
  waar_tekst:
    label: tekst
    type: textarea
    size: large
  waarom_titel:
    label: tekst
    type: textarea
    size: large
  waarom_sub_titel:
    label: tekst
    type: textarea
    size: large
  waarom_tekst:
    label: tekst
    type: textarea
    size: large
  bron_titel:
    label: tekst
    type: textarea
    size: large
      bron_sub_tekst:
    label: tekst
    type: textarea
    size: large
      bron_tekst:
    label: tekst
    type: textarea
    size: large